import type { LiveTransaction, FeedbackStats, SystemMetric, ChartDataPoint, PipelineNode } from '@/types'
import { generateMockTransaction, generateMockDecision } from './utils'

// Generate initial transaction stream
export function generateInitialTransactions(count = 12): LiveTransaction[] {
  return Array.from({ length: count }, (_, i) => {
    const txn = generateMockTransaction()
    txn.timestamp = new Date(Date.now() - (count - i) * 8000).toISOString()
    const decision = generateMockDecision(txn)
    return {
      ...txn,
      decision,
      status: decision.decision === 'block' ? 'blocked' : decision.decision === 'review' ? 'review' : 'approved',
      riskScore: decision.risk_score,
    }
  })
}

export const MOCK_FEEDBACK_STATS: FeedbackStats = {
  total_feedback: 1247,
  outcome_counts: {
    true_positive: 892,
    false_positive: 143,
    true_negative: 189,
    false_negative: 23,
  },
  missed_fraud_types: {
    card_testing: 8,
    cross_border_fraud: 7,
    account_takeover: 5,
    synthetic_identity: 3,
  },
  metrics: {
    precision: 0.8617,
    recall: 0.9749,
    f1_score: 0.9147,
    false_positive_rate: 0.0431,
  },
}

export const MOCK_SYSTEM_METRICS: SystemMetric[] = [
  { label: 'API Latency (p50)', value: '94ms', status: 'ok', trend: -3 },
  { label: 'API Latency (p99)', value: '312ms', status: 'ok', trend: 5 },
  { label: 'Redis', value: 'Connected', status: 'ok' },
  { label: 'SQLite Feedback DB', value: 'Online', status: 'ok' },
  { label: 'LLM API', value: 'Healthy', status: 'ok', trend: 1 },
  { label: 'Pipeline Latency', value: '187ms', status: 'ok', trend: -8 },
  { label: 'Graph Cache', value: '8,241 nodes', status: 'ok' },
  { label: 'Feature Store', value: '99.8% hit', status: 'ok', trend: 0 },
]

export function generateChartData(hours = 24): ChartDataPoint[] {
  return Array.from({ length: hours }, (_, i) => {
    const date = new Date(Date.now() - (hours - i) * 3600_000)
    const base = 120 + Math.sin(i * 0.4) * 40 + Math.random() * 20
    const fraud = Math.floor(base * (0.04 + Math.random() * 0.04))
    return {
      time: date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
      value: Math.floor(base),
      fraud,
      legitimate: Math.floor(base) - fraud,
    }
  })
}

export function generateRiskDistribution() {
  return [
    { range: '0–20', count: 4821, fill: '#22c55e' },
    { range: '20–40', count: 1203, fill: '#3b82f6' },
    { range: '40–60', count: 487, fill: '#eab308' },
    { range: '60–80', count: 198, fill: '#f97316' },
    { range: '80–100', count: 91, fill: '#ef4444' },
  ]
}

export function generateFraudTypeData() {
  return [
    { type: 'Card Testing', detected: 234, missed: 8, rate: 96.7 },
    { type: 'Account Takeover', detected: 189, missed: 5, rate: 97.4 },
    { type: 'Cross-Border', detected: 143, missed: 7, rate: 95.3 },
    { type: 'Synthetic Identity', detected: 87, missed: 3, rate: 96.7 },
    { type: 'Money Mule', detected: 65, missed: 1, rate: 98.5 },
    { type: 'Velocity Abuse', detected: 312, missed: 11, rate: 96.6 },
  ]
}

// Pipeline visualization nodes
export const PIPELINE_NODES: PipelineNode[] = [
  {
    id: 'transaction',
    label: 'Transaction Input',
    type: 'input',
    x: 400, y: 30,
    description: 'Raw transaction event arrives via REST API',
    purpose: 'Accept, validate, and deduplicate incoming transaction events from banking systems.',
    inputs: ['POST /detect payload'],
    outputs: ['Transaction object', 'User ID'],
    files: ['app/models/transaction.py', 'app/main.py'],
    latency: '< 1ms',
    auditScore: 82,
    testCount: 49,
    dependencies: [],
  },
  {
    id: 'fast_screening',
    label: 'Fast Screening',
    type: 'service',
    x: 400, y: 140,
    description: 'Stage 1: in-memory risk scoring in < 20ms',
    purpose: 'Apply velocity checks, amount anomaly detection, device novelty, location analysis, and feedback elevation to compute pre-risk score. Routes transaction to auto-approve or deep investigation.',
    inputs: ['Transaction', 'UserProfile', 'Feature Store cache', 'risk_elevation (feedback)'],
    outputs: ['pre_risk_score', 'screening_flags', 'routing_decision'],
    files: ['app/services/fast_screening.py'],
    latency: '< 20ms',
    auditScore: 91,
    testCount: 4,
    dependencies: ['feature_store', 'behavioral_similarity'],
  },
  {
    id: 'feature_store',
    label: 'Feature Store',
    type: 'service',
    x: 160, y: 140,
    description: 'Redis-backed behavioral feature cache',
    purpose: 'Precomputes and caches all user behavioral features: avg amounts, transaction velocity, known devices, location history, merchant frequencies, and feedback risk elevation.',
    inputs: ['User ID', 'Device ID', 'Merchant ID'],
    outputs: ['avg_amount_30d', 'txn_count_1h', 'known_devices', 'risk_elevation'],
    files: ['app/services/feature_store.py'],
    latency: '< 5ms',
    auditScore: 91,
    testCount: 3,
    dependencies: ['Redis'],
  },
  {
    id: 'behavior_agent',
    label: 'Behavior Agent',
    type: 'agent',
    x: 80, y: 300,
    description: 'LLM behavioral pattern analysis',
    purpose: 'Analyzes 30-day behavioral baseline vs current transaction. Detects deviations in spending patterns, timing, channel usage, and merchant preferences.',
    inputs: ['Transaction', 'UserProfile', 'feature_store data'],
    outputs: ['risk_score 0-100', 'key_findings', 'verdict'],
    files: ['app/agents/behavior_agent.py'],
    latency: '100-300ms',
    auditScore: 91,
    testCount: 12,
    dependencies: ['get_fast_llm()'],
  },
  {
    id: 'device_agent',
    label: 'Device Agent',
    type: 'agent',
    x: 240, y: 300,
    description: 'Device fingerprint & reputation analysis',
    purpose: 'Evaluates device trust score, fraud associations, account sharing, and device age. Detects new devices, device spoofing, and device-account mismatch.',
    inputs: ['Device ID', 'Device reputation', 'Known devices'],
    outputs: ['device_risk_score', 'trust_verdict', 'fraud_count'],
    files: ['app/agents/device_agent.py'],
    latency: '100-250ms',
    auditScore: 91,
    testCount: 12,
    dependencies: ['get_fast_llm()', 'device_reputation.py'],
  },
  {
    id: 'geo_agent',
    label: 'Geo Agent',
    type: 'agent',
    x: 400, y: 300,
    description: 'Geographic & travel risk analysis',
    purpose: 'Assesses location risk based on country risk tier, travel velocity (impossible travel), known locations, and cross-border patterns.',
    inputs: ['Location', 'IP Address', 'Travel profile', 'Known locations'],
    outputs: ['geo_risk_score', 'impossible_travel_flag', 'country_risk'],
    files: ['app/agents/geo_agent.py'],
    latency: '100-250ms',
    auditScore: 91,
    testCount: 12,
    dependencies: ['get_fast_llm()', 'geo_reputation.py'],
  },
  {
    id: 'merchant_agent',
    label: 'Merchant Agent',
    type: 'agent',
    x: 560, y: 300,
    description: 'Merchant reputation & category risk',
    purpose: 'Evaluates merchant chargeback rates, fraud associations, high-risk categories (crypto, wire transfer), and first-time merchant risk.',
    inputs: ['Merchant ID', 'Category', 'Merchant reputation'],
    outputs: ['merchant_risk_score', 'category_risk', 'chargeback_rate'],
    files: ['app/agents/merchant_agent.py'],
    latency: '100-250ms',
    auditScore: 91,
    testCount: 12,
    dependencies: ['get_fast_llm()', 'merchant_reputation.py'],
  },
  {
    id: 'graph_agent',
    label: 'Graph Agent',
    type: 'agent',
    x: 720, y: 300,
    description: 'Fraud network graph analysis',
    purpose: 'Detects shared devices, shared IPs, fraud rings, circular transactions, and high network centrality using a bounded LRU graph (10K nodes, NetworkX).',
    inputs: ['User ID', 'Device ID', 'IP Address', 'Merchant ID'],
    outputs: ['graph_risk_score', 'fraud_ring_detected', 'centrality_score'],
    files: ['app/agents/graph_agent.py', 'app/services/graph_intelligence.py'],
    latency: '15-50ms',
    auditScore: 91,
    testCount: 18,
    dependencies: ['graph_intelligence.py', 'NetworkX'],
  },
  {
    id: 'consensus',
    label: 'Consensus Engine',
    type: 'consensus',
    x: 400, y: 440,
    description: 'Weighted multi-agent risk aggregation',
    purpose: 'Aggregates 5 agent scores using weighted consensus. Missing agents redistribute weights proportionally. Agreement penalty applied for divergent scores.',
    inputs: ['5× AgentRisk', 'pre_risk_score'],
    outputs: ['consensus_score', 'weighted_risk', 'agent_agreement'],
    files: ['app/services/consensus_engine.py'],
    latency: '< 2ms',
    auditScore: 91,
    testCount: 5,
    dependencies: ['behavior_agent', 'device_agent', 'geo_agent', 'merchant_agent', 'graph_agent'],
  },
  {
    id: 'investigation',
    label: 'Deep Investigation',
    type: 'agent',
    x: 400, y: 560,
    description: 'Cross-agent reasoning & kill chain analysis',
    purpose: 'If risk ≥ threshold: deep LLM investigation combining all agent evidence with kill chain stages, sequence intelligence, cohort analysis, and negative signals.',
    inputs: ['All agent outputs', 'Evidence package', 'Kill chain', 'Sequences'],
    outputs: ['investigation_findings', 'kill_chain_stage', 'sequence_alerts'],
    files: ['app/agents/investigation_agent.py', 'app/services/kill_chain.py', 'app/services/sequence_intelligence.py'],
    latency: '300-800ms',
    auditScore: 91,
    testCount: 8,
    dependencies: ['get_deep_llm()', 'kill_chain', 'sequence_intelligence', 'cohort_analysis'],
  },
  {
    id: 'counterfactual',
    label: 'Counterfactual',
    type: 'agent',
    x: 200, y: 680,
    description: 'What-if scenario generation',
    purpose: 'Generates counterfactual explanations: what minimum changes to the transaction would alter the decision. Deterministic primary path with LLM enhancement.',
    inputs: ['Transaction', 'FraudDecision', 'risk_score'],
    outputs: ['counterfactual_explanation', 'contributing_factors'],
    files: ['app/agents/counterfactual_agent.py'],
    latency: '50-400ms',
    auditScore: 91,
    testCount: 10,
    dependencies: ['_SIGNAL_WEIGHTS', 'get_fast_llm()'],
  },
  {
    id: 'explainability',
    label: 'Explainability',
    type: 'agent',
    x: 400, y: 680,
    description: 'Human-readable fraud explanation',
    purpose: 'Generates regulatory-grade natural language explanation of the fraud decision, combining all evidence into a coherent narrative with specific signal citations.',
    inputs: ['All evidence', 'Signals', 'AgentRisks', 'ConsensusScore'],
    outputs: ['explanation_text', 'key_risk_factors'],
    files: ['app/agents/explainability_agent.py'],
    latency: '200-500ms',
    auditScore: 91,
    testCount: 8,
    dependencies: ['get_deep_llm()', 'evidence_builder'],
  },
  {
    id: 'storytelling',
    label: 'Story Narrative',
    type: 'agent',
    x: 600, y: 680,
    description: 'Analyst-facing narrative generation',
    purpose: 'Creates a structured investigation narrative for human analysts: transaction timeline, risk factors, recommended actions, and next investigation steps.',
    inputs: ['Transaction', 'Evidence', 'Decision'],
    outputs: ['story_narrative', 'recommended_action'],
    files: ['app/agents/storytelling_agent.py'],
    latency: '200-400ms',
    auditScore: 91,
    testCount: 6,
    dependencies: ['get_fast_llm()'],
  },
  {
    id: 'feedback_store',
    label: 'Feedback Store',
    type: 'feedback',
    x: 180, y: 820,
    description: 'SQLite analyst decision persistence',
    purpose: 'Append-only SQLite store for analyst corrections (TP/FP/TN/FN). Deduplication, high-watermark processing, and full audit trail for pattern changes.',
    inputs: ['Analyst decision', 'device_id', 'merchant_id', 'outcome_label'],
    outputs: ['feedback_id', 'dedup_check', 'processed_at watermark'],
    files: ['app/feedback/feedback_store.py'],
    latency: '< 10ms',
    auditScore: 86,
    testCount: 15,
    dependencies: ['SQLite (aiosqlite)'],
  },
  {
    id: 'pattern_evolution',
    label: 'Pattern Evolution',
    type: 'feedback',
    x: 400, y: 820,
    description: 'Adaptive fraud pattern learning',
    purpose: 'Analyzes false negatives to boost signal weights and lower detection thresholds for missed fraud types. Nudges thresholds up for well-performing patterns. Optional LLM-based new pattern discovery.',
    inputs: ['FeedbackStats', 'missed_fraud_types', 'fraud_patterns.json'],
    outputs: ['threshold adjustments', 'signal weight boosts', 'pattern_updates audit trail'],
    files: ['app/feedback/pattern_evolution.py', 'app/data/fraud_patterns.json'],
    latency: '10-500ms',
    auditScore: 89,
    testCount: 12,
    dependencies: ['get_fast_llm() (optional)', 'feedback_store'],
  },
  {
    id: 'reputation_updater',
    label: 'Reputation Updater',
    type: 'feedback',
    x: 620, y: 820,
    description: 'Device & merchant trust score updates',
    purpose: 'Updates device and merchant reputation in Redis based on confirmed outcomes. Uses high-watermark to prevent double-processing. TP/FN penalize, FP restores.',
    inputs: ['Unprocessed feedback records (device_id, merchant_id)'],
    outputs: ['Redis device/merchant reputation', 'risk_elevation for future screening'],
    files: ['app/feedback/reputation_updater.py'],
    latency: '< 50ms',
    auditScore: 94,
    testCount: 10,
    dependencies: ['feature_store', 'feedback_store'],
  },
  {
    id: 'future_detection',
    label: 'Future Detection ↑',
    type: 'output',
    x: 400, y: 950,
    description: 'Improved detection on subsequent transactions',
    purpose: 'The full feedback loop closes: reputation updates affect fast_screening scores, pattern changes improve fraud_patterns matching, and risk_elevation flags confirmed fraudsters.',
    inputs: ['Updated reputations', 'Evolved patterns', 'risk_elevation in feature store'],
    outputs: ['Higher recall', 'Lower false positives', 'Better calibrated thresholds'],
    files: ['app/services/fast_screening.py (risk_elevation)', 'app/data/fraud_patterns.json'],
    latency: 'Next transaction',
    auditScore: 91,
    dependencies: ['feedback_store', 'pattern_evolution', 'reputation_updater'],
  },
]

export const ARCHITECTURE_MODULES = [
  {
    id: 'simulation',
    name: 'Synthetic Data Generation',
    icon: '🔬',
    files: 12,
    tests: 84,
    auditScore: 63,
    status: 'production',
    purpose: 'Generates realistic fraud scenarios with 8 persona types, 6 campaign types, 5 ring types, adversarial mutations, and 4 evolution generations.',
    dependencies: ['world_builder', 'temporal_simulator', 'population_simulator'],
    lines: 3200,
  },
  {
    id: 'pipeline',
    name: 'Detection Pipeline',
    icon: '⚡',
    files: 1,
    tests: 26,
    auditScore: 87,
    status: 'production',
    purpose: 'LangGraph-based orchestration: Fast Screening → Parallel Agents → Consensus → Investigation → Explainability → Storytelling.',
    dependencies: ['agents', 'services', 'feature_store'],
    lines: 680,
  },
  {
    id: 'agents',
    name: 'AI Agents (10)',
    icon: '🤖',
    files: 12,
    tests: 103,
    auditScore: 91,
    status: 'production',
    purpose: '10 specialized LangChain agents: 5 parallel analysis (Behavior, Device, Geo, Merchant, Graph) + Investigation + Counterfactual + Explainability + Analyst + Storytelling.',
    dependencies: ['_llm_clients', '_agent_base', 'services'],
    lines: 2100,
  },
  {
    id: 'services',
    name: 'Services & Intelligence (15)',
    icon: '🧠',
    files: 15,
    tests: 70,
    auditScore: 91,
    status: 'production',
    purpose: '15 deterministic intelligence services: fast_screening, graph_intelligence (LRU bounded), consensus_engine, sequence_intelligence, kill_chain, cohort_analysis, and 9 others.',
    dependencies: ['feature_store', 'Redis', 'NetworkX'],
    lines: 4800,
  },
  {
    id: 'feedback',
    name: 'Feedback Loop (3)',
    icon: '🔄',
    files: 3,
    tests: 40,
    auditScore: 91,
    status: 'production',
    purpose: 'Analyst feedback → pattern evolution → reputation updates → improved future detection. Fully closed loop.',
    dependencies: ['SQLite', 'Redis', 'pattern_evolution'],
    lines: 640,
  },
  {
    id: 'models',
    name: 'Data Models',
    icon: '📐',
    files: 4,
    tests: 84,
    auditScore: 82,
    status: 'production',
    purpose: 'Pydantic v2 models with full validation: Transaction, UserProfile, Evidence, FraudDecision.',
    dependencies: ['Pydantic v2'],
    lines: 480,
  },
  {
    id: 'api',
    name: 'FastAPI Backend',
    icon: '🌐',
    files: 1,
    tests: 0,
    auditScore: 78,
    status: 'production',
    purpose: '40+ REST endpoints: detect, profiles, simulation, feedback, metrics, graph, scenarios.',
    dependencies: ['FastAPI', 'uvicorn', 'all modules'],
    lines: 610,
  },
]
